name: BminsRelics
main: frostfire.bminsrelics.Bminsrelics
version: 0.0.1
description: A really cool plugin for relics and a few other things probably
commands:
  relic:
    description: Gives a relic
    usage: /<command>